language: node_js
dist: trusty
sudo: required
node_js: stable
services:
  - docker
install:
  - npm install
  - docker run -p 8545:8545 foamspace/cliquebait:latest -d
  - npm run truffle
  - npm run test
script:
  - bower install --production
  - npm run -s build
  - bower install
  - npm -s test
