language: node_js
dist: trusty
sudo: required
node_js: stable
services:
  - docker
install:
  - make install
  - make compile-contracts
script:
  - docker run -d -p 8545:8545 foamspace/cliquebait:latest
  - sleep 10
  - make deploy
  - make test
