language: node_js
dist: trusty
sudo: required
node_js: stable
services:
  - docker
install:
  - npm install
script:
  - docker run -d -p 8545:8545 foamspace/cliquebait:latest
  - sleep 10
  - npm run truffle
  - npm run test
